stat_scv (ТЗ 17) ver 1.0
Lilyziz/java-explore-with-me pull request #3
Opened 2023-09-10 16:32 UTC by Lilyziz

2023-09-10 19:26 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-09-10 19:26 UTC, FanaticFiz commented on ewm-service/src/main/resources/application.properties
> +server.port=8081
Перейдем на `YAML` формат?

2023-09-10 19:26 UTC, FanaticFiz commented on pom.xml
> +    <dependencies>
Тут нужно быть аккуратнее с зависимостями, ведь они будут у всех сервисов которые наследуют этого родителя.

2023-09-10 19:26 UTC, FanaticFiz commented on stats-service/pom.xml
> +        <module>stats-DTO</module>
`stats-DTO` почему большие буквы? Это нарушение правил именования...

2023-09-10 19:26 UTC, FanaticFiz commented on stats-service/stats-DTO/pom.xml
> +        <java.version>11</java.version>
А вот версия, например, наоборот, может быть указана единожды, только у родительского `pom`

2023-09-10 22:19 UTC, Lilyziz commented on pom.xml
> +    <dependencies>
Если я правильно поняла, то в одном из наследников был дубль зависимости из родительского pom'а.

2023-09-11 03:54 UTC, FanaticFiz approved these changes

2023-09-11 07:58 UTC, merged