main_svc (ТЗ 17.2) v1.0
Lilyziz/java-explore-with-me pull request #4
Opened 2023-09-26 16:31 UTC by Lilyziz

2023-09-28 11:12 UTC, Lilyziz commented
Ох, если бы я не промучилась с 16ТЗ и не попала бы на когорту ниже, я бы наверное никогда ЭТО не осилила в такие сроки. Читала вместо одного чата в телеге целых два. Все ошибки, с которыми я сталкивалась, обсуждали уже там до меня.

2023-09-28 20:17 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-09-28 20:17 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/main/service/publicService/PublicEventService.java
> +        if (categories.size() < 1 || (text != null && text.length() < 2)) {
`categories.size() < 1` ---> `categories.isEmpty()`

2023-09-28 20:17 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/main/controller/publicController/PublicEventController.java
> +                                      HttpServletRequest request) throws IOException, InterruptedException {
Нет смысла в указании `throws IOException, InterruptedException` тут

2023-09-28 20:17 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/main/stats/StatsServer.java
> +                httpClient.postHit(host, "{\"app\":\"ewm-main-service\"," +
Это какое-то баловство! ))
Почему мы тут лепим строками объект, должна быть модель: `EndpointHitDto`

2023-09-28 20:17 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/main/stats/StatsServer.java
> +        HttpResponse<String> httpResponse =
`httpResponse` - не используется...

2023-09-28 20:17 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/main/stats/StatsServer.java
> +    ConfigClient configClient;
Куда подевались все модификаторы доступа?

2023-09-28 20:17 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/main/service/adminService/AdminCategoryService.java
> +import lombok.AllArgsConstructor;
Много где не подчищены импорты.

![image](https://github.com/Lilyziz/java-explore-with-me/assets/3994663/8119baa6-1fcc-4ad7-b49e-85115d23eae9)

2023-09-28 20:17 UTC, FanaticFiz commented on stats-service/stats-client/pom.xml
> +            <groupId>junit</groupId>
Зависимости дублируются...
`junit`

2023-09-28 20:17 UTC, FanaticFiz commented on ewm-service/pom.xml
> +                <artifactId>maven-surefire-plugin</artifactId>
`maven-surefire-plugin` - описан дважды!

2023-09-28 21:18 UTC, Lilyziz commented
Я перестаю понимать что-либо. Удаляю банальный комментарий, начинаются проблемы с докером...

2023-09-28 21:23 UTC, Lilyziz commented
Ну вот я удалила дубликат, и всё умерло

2023-09-28 21:52 UTC, Lilyziz commented
Удаляю один импорт - перестаёт запускаться проект.
![image](https://github.com/Lilyziz/java-explore-with-me/assets/18059808/27aed756-e137-42d0-86f3-4eee1546704c)

2023-09-29 00:24 UTC, Lilyziz commented
На первый взгляд показалось, что исправления пустяковые.
Но я была в шоке, когда я убрала только неиспользуемые импорты, и всё перестало работать... 
Я исправила всё, кроме колхоза в StatsServer. Написала в комментарии что по идее должно быть, но не понимаю в чём проблема.

2023-09-29 19:10 UTC, FanaticFiz approved these changes

2023-09-29 19:10 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/main/stats/StatsServer.java
> +        //        .toString());
Может тут банально `toString` не дает строку в нужном формате.

2023-10-01 18:28 UTC, merged