feature_comment (ТЗ 17.3) v1.0
Lilyziz/java-explore-with-me pull request #5
Opened 2023-10-02 10:15 UTC by Lilyziz

2023-10-02 14:43 UTC, Lilyziz commented
Я так тот колхоз и не посмотрела если честно.
Мне сегодня написали, что сдать фичу надо, внезапно, сегодня. У меня аж вся земля из под ног ушла. А в итоге надо отправить на 1 ревью, а весь диплом закончить до пятницы. Хотя раньше информация была другая, времени было больше.
Поэтому сделала комментарии без всяких украшений.

2023-10-02 19:41 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-10-02 19:41 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/main/service/privateService/IPrivateUserCommentService.java
> +package ru.practicum.main.service.privateService;
Название пакета не по java-овски
Правильно будет: `private_service`

2023-10-02 19:41 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/main/service/privateService/PrivateUserCommentService.java
> +                () -> new NotFoundException("User was not found"));
```
User user = userRepository.findById(userId).orElseThrow(
                () -> new NotFoundException("User was not found"));
```

И так мы пишем в каждом сервисе!
Почему бы не написать это один раз в `userService`, и подключать именно сервис, а не репозиторий?

Тоже самое и с сущностью `event` и другими.
У сервиса должны быть веские причины чтобы брать "чужой" репозиторий.

2023-10-02 22:13 UTC, Lilyziz commented
Решила проблему с тем самым кринжем. Дело было в том, что из properties я подтягивала app.name в static переменную, а так делать было нельзя.

2023-10-03 18:26 UTC, FanaticFiz approved these changes

2023-10-03 19:44 UTC, merged